#pragma once

#define CAPS_WORD_IDLE_TIMEOUT 1000
#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
// #define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD
// #define CAPS_WORD_TOGGLE_KEY

// #define LEADER_PER_KEY_TIMING
// #define LEADER_TIMEOUT 250

#define COMBO_TERM 25
#define PERMISSIVE_HOLD
#define TAPPING_TERM 175
#define TAPPING_TOGGLE 2
// #define QUICK_TAP_TERM 200 // Affects TT()

// sm_td
#define MAX_DEFERRED_EXECUTORS 10

// achordion
#define ACHORDION_STREAK

// RGB
#define RGB_MATRIX_TIMEOUT 300000
#define RGB_MATRIX_DEFAULT_VAL 15
