#pragma once

#define PERMISSIVE_HOLD
#define TAPPING_TOGGLE 2
#define QUICK_TAP_TERM 100 // Messes up TAPPING_TOGGLE for some reason

// Caps Word
#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
// #define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD

// VIA
#define DYNAMIC_KEYMAP_LAYER_COUNT 7

// UEFI was not detecting some of my boards
#define SPLIT_WATCHDOG_ENABLE
#define SPLIT_MAX_CONNECTION_ERRORS 30
#define SPLIT_CONNECTION_CHECK_TIMEOUT 500
#define SPLIT_USB_DETECT
#define SPLIT_USB_TIMEOUT 1000
#define SPLIT_USB_TIMEOUT_POLL 20
#define SPLIT_WATCHDOG_TIMEOUT 5000
